instagram-to-kafka-service:
  instagram-keywords:
    - amazonwebservices
    - aws
    - azurecloud
    - docker
    - elasticsearch
    - git
    - googlecloud
    - html
    - javaprogramming
    - javascript
    - linux
    - microservices
    - mongodb
    - nosql
    - postgresql
    - softwareengineering
    - springboot
    - sql
    - webdeveloper
    - webdevelopment
  welcome-message: Hello Folks!
  ig-access-token: ${ACCESS_TOKEN}
  ig-user-id: ${IG_USER_ID}
  poll-interval-seconds: 60000

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000

kafka-config:
  bootstrap-servers: kafka-broker-1:9092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://schema-registry:8081
  topic-name: ig-topic
  topic-names-to-create:
    - ig-topic
  num-of-partitions: 1
  replication-factor: 1

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.LongSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: snappy
  acks: all
  batch-size: 16384
  batch-size-boost-factor: 100
  linger-ms: 5
  request-timeout-ms: 60000
  retry-count: 5

spring:
  kafka:
    bootstrap-servers: kafka-broker-1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://schema-registry:8081